apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: workload.kcp.io
spec:
  latestResourceSchemas:
  - v230202-bc98b021.synctargets.workload.kcp.io
status: {}
